catalog/urls.py
from django.urls import path

from catalog.views import (
    index,
    BookListView,
    BookDetailView,
    BookCreateView,
    BookUpdateView,

    AuthorListView,
    AuthorDetailView,
    AuthorCreateView,

    LiteraryFormatListView,
    LiteraryFormatCreateView,
    LiteraryFormatUpdateView,
    LiteraryFormatDeleteView,

)

urlpatterns = [
    path("", index, name="index"),
    path("literary-formats/", LiteraryFormatListView.as_view(), name="literary-formats-list"),
    path("literary-formats/create", LiteraryFormatCreateView.as_view(), name="literary-formats-create"),
    path("literary-formats/<int:pk>update/", LiteraryFormatUpdateView.as_view(), name="literary-formats-update"),
    path("literary-formats/<int:pk>delete/", LiteraryFormatDeleteView.as_view(), name="literary-formats-delete"),
    path("books/", BookListView.as_view(), name="book-list"),
    path("books/<int:pk>/", BookDetailView.as_view(), name="book-detail"),
    path("books/create", BookCreateView.as_view(), name="book-create"),
    path("books/<int:pk>/update/", BookUpdateView.as_view(), name="book-update"),

    path("authors/", AuthorListView.as_view(), name="author-list"),
    path("authors/<int:pk>/", AuthorDetailView.as_view(), name="author-detail"),
    path("authors/create", AuthorCreateView.as_view(), name='author-create'),

]

app_name = "catalog"

library/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path("admin/", admin.site.urls),
    path("catalog/", include("catalog.urls", namespace="catalog")),
    path("accounts/", include("django.contrib.auth.urls")),
    path("__debug__/", include("debug_toolbar.urls")),
]

catalog/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.urls import reverse

from library import settings


class LiteraryFormat(models.Model):
    name = models.CharField(max_length=255)

    class Meta:
        ordering = ("name", )

    def __str__(self):
        return self.name


class Author(AbstractUser):
    pseudonym = models.CharField(max_length=63, null=True, blank=True)
    class Meta:
        ordering = ("username", )

    def __str__(self):
        return f"{self.first_name} {self.last_name}"

class Book(models.Model):
    title = models.CharField(max_length=255)
    price = models.DecimalField(max_digits=7, decimal_places=2)
    format = models.ForeignKey(
        LiteraryFormat,
        on_delete=models.CASCADE,
        related_name="books"
    )
    author = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name="books")

    class Meta:
        ordering = ("title", )

    def __str__(self):
        return f"{self.title} (price: {self.price}, format: {self.format})"

    def get_absolute_url(self):
        return reverse("catalog:book-detail", args=[str(self.id)])

catalog/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm

from .models import Author, Book


class AuthorCreationForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = Author
        fields = UserCreationForm.Meta.fields + ("first_name", "last_name", "pseudonym",)


class BookForm(forms.ModelForm):
    author = forms.ModelMultipleChoiceField(
        queryset=get_user_model().objects.all(),
        widget=forms.CheckboxSelectMultiple,
        required=False
    )
    class Meta:
        fields = "__all__"
        model = Book

catalog/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required
from django.urls import reverse, reverse_lazy
from django.views import generic
from django.http import HttpRequest, HttpResponse, HttpResponseRedirect
from django.shortcuts import render

from .forms import AuthorCreationForm, BookForm
from .models import Book, Author, LiteraryFormat


@login_required
def index(request: HttpRequest) -> HttpResponse:
    num_books = Book.objects.count()
    num_authors = Author.objects.count()
    num_formats = LiteraryFormat.objects.count()
    num_visits = request.session.get("num_visits", 0)
    request.session["num_visits"] = num_visits + 1

    context = {
        "num_books": num_books,
        "num_authors": num_authors,
        "num_formats": num_formats,
        "num_visits": num_visits + 1,
    }
    return render(request, "catalog/index.html", context=context)


class LiteraryFormatListView(LoginRequiredMixin, generic.ListView):
    model = LiteraryFormat
    template_name = "catalog/literary_format_list.html"
    context_object_name = "literary_format_list"


class LiteraryFormatCreateView(LoginRequiredMixin, generic.CreateView):
    model = LiteraryFormat
    fields = "__all__"
    success_url = reverse_lazy("catalog:literary-formats-list")
    template_name = "catalog/literary_format_form.html"


class LiteraryFormatUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = LiteraryFormat
    fields = "__all__"
    success_url = reverse_lazy("catalog:literary-formats-list")
    template_name = "catalog/literary_format_form.html"


class LiteraryFormatDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = LiteraryFormat
    success_url = reverse_lazy("catalog:literary-formats-list")
    template_name = "catalog/literary_format_confirm_delete.html"


class BookListView(LoginRequiredMixin, generic.ListView):
    model = Book
    queryset = Book.objects.select_related("format")
    paginate_by = 10


class BookDetailView(LoginRequiredMixin, generic.DetailView):
    model = Book


class BookCreateView(LoginRequiredMixin, generic.CreateView):
    model = Book
    form_class = BookForm


class BookUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Book
    form_class = BookForm

class AuthorListView(LoginRequiredMixin, generic.ListView):
    model = Author
    queryset = Author.objects.prefetch_related("books")


class AuthorCreateView(LoginRequiredMixin, generic.CreateView):
    model = Author
    form_class = AuthorCreationForm


class AuthorDetailView(LoginRequiredMixin, generic.DetailView):
    model = Author
    queryset = Author.objects.all().prefetch_related("books")

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  {% block title %}
    <title>Library</title>
  {% endblock %}
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta charset="UTF-8">
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css"
        integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N" crossorigin="anonymous">
  {% load static %}
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>
<body>
<div class="container-fluid">
  <div class="row">
    <div class="col-sm-3">
      {% block sidebar %}
        {% include "includes/sidebar.html" %}
      {% endblock %}
    </div>
    <div class="col-9">
      {% block content %}
      {% endblock %}
      {% block pagination %}
        {% include 'includes/pagination.html' %}
      {% endblock %}
    </div>
  </div>
</div>
</body>
</html>

templates/catalog/author_detail.html
{% extends "base.html" %}

{% block content %}
  <h1>
    Author`s page:
    <p>{{ author.first_name }} {{ author.last_name }}</p>
    <a href="#" class="btn btn-secondary">Update</a>
    <a href="#" class="btn btn-danger">Delete</a>
  </h1>
{% endblock %}

templates/catalog/author_form.html
{% extends 'base.html' %}

{% block content %}
  <h1>Create account</h1>

  <form action="" method="post" novalidate>
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Submit">
  </form>
{% endblock %}

templates/catalog/author_list.html
{% extends 'base.html' %}

{% block content %}
  {% if author_list %}
    <h1>
      All authors:
      <a href="{% url 'catalog:author-create' %}" class="btn btn-primary link-to-page">Create</a>
    </h1>
    <ul>
      {% for author in author_list %}
        <li class="list-item">
          {{ author.id }}:
          <a href="{% url 'catalog:author-detail' pk=author.id %}">
            {{ author.first_name }} {{ author.last_name }}
          </a>
        </li>
      {% endfor %}
    </ul>
  {% else %}
    <h1>There are no authors</h1>
  {% endif %}
{% endblock %}

templates/catalog/book_detail.html
{% extends "base.html" %}

{% block title %}
  <title>{{ book.title }} | Library</title>
{% endblock %}

{% block content %}
  <h1>{{ book.title }}</h1>
  <p><strong>Price:</strong> {{ book.price }}</p>
  <p><strong>Format:</strong> {{ book.format.name }}</p>

  <div class="ml-3">
    <h3>Authors</h3>
    {% if book.author.all %}
      {% for author in book.author.all %}
        <hr>
        <p>{{ author.id }}</p>
        <p>{{ author.first_name }} {{ author.last_name }}
          {% if author.pseudonym %}
            {{ author.pseudonym }}
          {% endif %}
        </p>
      {% endfor %}
    {% else %}
      <p>No authors assigned.</p>
    {% endif %}
    <a href="{% url 'catalog:book-update' pk=book.id %}" class="btn btn-secondary">Update</a>
    <a href="#" class="btn btn-danger">Delete</a>
  </div>
{% endblock %}

templates/catalog/book_form.html
{% extends "base.html" %}

{% load crispy_forms_tags %}
{% block content %}
  <h1>{{ object|yesno:"Update,Create new" }} book</h1>

  <form action="" method="post" novalidate>
    {% csrf_token %}
    {{ form|crispy }}
    <input class="btn btn-primary" type="submit" value="Submit">
  </form>
{% endblock %}

templates/catalog/book_list.html
{% extends "base.html" %}

{% block content %}
  <h1>
    Book List
    <a href="{% url 'catalog:book-create' %}" class="btn btn-primary link-to-page">Create</a>
  </h1>
  {% if book_list %}
    <ul>
      {% for book in book_list %}
        <li class="books">
          <a href="{{ book.get_absolute_url }}">
            {{ book.title }}
          </a>
        </li>
      {% endfor %}
    </ul>
  {% else %}
    <p>
      There is no books
    </p>
  {% endif %}
{% endblock %}

templates/catalog/index.html
{% extends "base.html" %}
{% block title %}
  <title> Home page</title>
{% endblock %}

{% block content %}
  <h1>Library Home</h1>
  <p>Welcome to the greatest library</p>
  <h3>Library content:</h3>
  <ul>
    <li>Num books: {{ num_books }}</li>
    <li>Num authors: {{ num_authors }}</li>
    <li>Num literary formats: {{ num_formats }}</li>
  </ul>
  <p>You have visited this page {{ num_visits }} time{{ num_visits|pluralize }}</p>
{% endblock %}

templates/catalog/literary_format_confirm_delete.html
{% extends "base.html" %}


{% block content %}
  <h1>Delete literary format</h1>

  <p>Are you sure you want to delete the literary format: {{ literaryformat }}?</p>
  <p><i>All Books with this literary format will be also deleted!</i></p>
  <form action="" method="post">
    {% csrf_token %}
    <a href="javascript:history.back()" class="btn btn-secondary">Cancel</a>
    <input type="submit" value="Yes, delete" class="btn btn-danger">
  </form>

{% endblock %}

templates/catalog/literary_format_form.html
{% extends "base.html" %}

{% load crispy_forms_tags %}
{% block content %}
  <h1>{{ object|yesno:"Update,Create new" }} literary format</h1>

  <form action="" method="post" novalidate>
    {% csrf_token %}
    {{ form|crispy }}
    <input class="btn btn-primary" type="submit" value="Submit">
  </form>
{% endblock %}

templates/catalog/literary_format_list.html
{% extends "base.html" %}

{% block content %}
  <h1>
    Literary format list
    <a href="{% url 'catalog:literary-formats-create' %}" class="btn btn-primary link-to-page">Create</a>
  </h1>
  {% if literary_format_list %}
    <table class="table">
      <tr>
        <th>ID</th>
        <th>Name</th>
        <th>Update</th>
        <th>Delete</th>
      </tr>

      {% for literary_format in literary_format_list %}
        <tr>
          <td>
            {{ literary_format.id }}
          </td>
          <td>
            {{ literary_format.name }}
          </td>
          <td>
            <a href="{% url 'catalog:literary-formats-update' pk=literary_format.id %}">UPDATE</a>
          </td>
          <td>
            <a href="{% url 'catalog:literary-formats-delete' pk=literary_format.id %}">DELETE</a>
          </td>
        </tr>
      {% endfor %}


    </table>
  {% else %}
    <p>There is no literary formats</p>
  {% endif %}
{% endblock %}

templates/includes/pagination.html
{% if is_paginated %}
  <ul class="pagination">
    {% if page_obj.has_previous %}
      <li class="page-item"><a href="?page={{ page_obj.previous_page_number }}" class="page-link">Prev</a></li>
    {% endif %}
    <li class="page-item active"><span class="page-link">{{ page_obj.number }} of {{ paginator.num_pages }}</span></li>
    {% if page_obj.has_next %}
      <li class="page-item"><a href="?page={{ page_obj.next_page_number }}" class="page-link">Next</a></li>
    {% endif %}
  </ul>
{% endif %}

templates/includes/sidebar.html
<ul class="sidebar-nav list-group">
  {% if user.is_authenticated %}
    <li class="list-group-item">User: {{ user.first_name }} {{ user.last_name }}</li>
    <li>
      <form action="{% url 'logout' %}" method="post">
        {% csrf_token %}
        <button type="submit" class="btn btn-primary" style="margin-top: 10px">Log out</button>
      </form>
    </li>
    <br>
  {% else %}
    <li class="list-group-item">
      <a href="{% url 'login' %}">Log in</a>
    </li>
    <li class="list-group-item">
      <a href="{% url 'catalog:author-create' %}">Create new account</a>
    </li>
    <br>
  {% endif %}

  <li class="list-group-item">
    <a href="{% url 'catalog:index' %}">Home</a>
  </li>
  <li class="list-group-item">
    <a href="{% url 'catalog:author-list' %}">All authors</a>
  </li>
  <li class="list-group-item">
    <a href="{% url 'catalog:book-list' %}">All books</a>
  </li>
  <li class="list-group-item">
    <a href="{% url 'catalog:literary-formats-list' %}">All literary formats</a>
  </li>
</ul>